@echo off
setlocal EnableExtensions

set SYMBOLS=BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT,DOGEUSDT,ADAUSDT,AVAXUSDT,SHIBUSDT,LINKUSDT,DOTUSDT,LTCUSDT,BCHUSDT,UNIUSDT,TONUSDT,NEARUSDT,XLMUSDT,HBARUSDT,ATOMUSDT,VETUSDT,FILUSDT,ICPUSDT,ETCUSDT,APTUSDT,ARBUSDT,OPUSDT,MATICUSDT,INJUSDT,TIAUSDT,SEIUSDT,XAUTUSDT,PAXGUSDT,GLMRUSDT,KASUSDT,SUIUSDT,STXUSDT,FTMUSDT,RUNEUSDT,EOSUSDT,ALGOUSDT
set TIMEFRAME=all
set EPOCHS=2
set BATCH_SIZE=2
set GRAD_ACCUM_STEPS=8
set LEARNING_RATE=0.0002
set MAX_SEQ_LENGTH=512
set BASE_MODEL_ID=amazon/chronos-2
set BASE_MODEL_FALLBACK_ID=amazon/chronos-t5-large
set HF_FORCE_DOWNLOAD=1
set HF_LOCAL_FILES_ONLY=0
set FORCE_CPU=0
set CHRONOS2_TRAIN_STEPS=

if /I "%DATA_BUCKET%"=="dummy-bucket" set DATA_BUCKET=
if /I "%DATA_S3_BUCKET%"=="dummy-bucket" set DATA_S3_BUCKET=
if /I "%MODEL_BUCKET%"=="dummy-model" set MODEL_BUCKET=

call "%~dp0run-train-gpu.bat" %*
exit /b %ERRORLEVEL%
